FROM node:18-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend .
RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install --only=production
COPY frontend/server.js ./server.js
COPY frontend/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
